-- Demo invoices: every status, tags, folders, NGN with a USD equivalent,
-- a USD invoice with a naira equivalent, discounts, charges, part and over payments.
-- Generated by a script so every stored total matches the app's own maths.
-- Local:  npm run db:seed:local
-- Remove: DELETE FROM invoices WHERE id LIKE 'inv_demo_%';

INSERT OR IGNORE INTO tags (id, name, color, created_at) VALUES
  ('tag_client', 'Client', 'yellow', 0),
  ('tag_retainer', 'Retainer', 'green', 0),
  ('tag_international', 'International', 'blue', 0);

INSERT OR IGNORE INTO folders (id, name, color, created_at) VALUES
  ('fld_client', 'Client work', 'blue', 0);

DELETE FROM invoices WHERE id IN ('inv_demo1', 'inv_demo2', 'inv_demo3', 'inv_demo4') OR id LIKE 'inv_demo_%';

INSERT INTO invoices (id, number, client_name, client_email, client_address, issued_at, due_at, currency, status,
  items, payments, subtotal, tax_rate, discount, discount_type, charges, payment_method, equivalent_amount,
  exchange_rate, total, notes, terms, folder, tag, avatar, created_at, updated_at) VALUES
  ('inv_demo_01', 'DEMO-0001', 'Lagos Bistro Group', 'accounts@lagosbistro.ng', 'Lagos Bistro Group
Funmi Adebayo
14 Admiralty Way, Lekki Phase 1
Lagos
Nigeria', CAST(strftime('%s', date('now', '+0 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '+30 days')) AS INTEGER) * 1000, 'NGN', 'draft', '[{"name": "Website redesign", "desc": "Discovery, wireframes and visual design for 6 pages", "qty": 1, "unitPrice": 850000}, {"name": "CMS build", "desc": "Next.js + headless CMS, content migration", "qty": 1, "unitPrice": 450000}, {"name": "Content writing", "desc": "Per page", "qty": 6, "unitPrice": 25000}]', '[]', 1450000.0, 0.075, 0, 'value', 0, 'Bank transfer', 0, 0, 1558750.0, 'Draft for review: scope agreed on the 2 Oct call.', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', 'Client', 'NC', CAST(strftime('%s', date('now', '+0 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '+0 days')) AS INTEGER) * 1000),
  ('inv_demo_02', 'DEMO-0002', 'Halcyon Health', 'finance@halcyonhealth.ng', 'Halcyon Health
Dr. Kemi Okafor
Plot 22 Ademola Adetokunbo Crescent
Wuse II, Abuja
Nigeria', CAST(strftime('%s', date('now', '-2 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '+12 days')) AS INTEGER) * 1000, 'NGN', 'sent', '[{"name": "Monthly support retainer (October)", "desc": "20 hours of maintenance, monitoring and fixes", "qty": 1, "unitPrice": 600000}, {"name": "Additional support hours", "desc": "Beyond the retainer allowance", "qty": 4, "unitPrice": 30000}]', '[]', 720000.0, 0.075, 0, 'value', 0, 'Bank transfer', 0, 0, 774000.0, '', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', 'Retainer', 'NC', CAST(strftime('%s', date('now', '-2 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-2 days')) AS INTEGER) * 1000),
  ('inv_demo_03', 'DEMO-0003', 'Northbeam Labs Inc.', 'ap@northbeam.io', 'Northbeam Labs Inc.
Sarah Chen
535 Mission Street, Suite 1400
San Francisco, CA 94105
United States', CAST(strftime('%s', date('now', '-5 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '+25 days')) AS INTEGER) * 1000, 'NGN', 'sent', '[{"name": "Mobile app UX audit", "desc": "Heuristic review, 12 recorded user sessions, report", "qty": 1, "unitPrice": 1900000}, {"name": "Design system tokens", "desc": "", "qty": 1, "unitPrice": 1200000}]', '[]', 3100000.0, 0.0, 0, 'value', 0, 'Wire transfer', 0, 1550, 3100000.0, 'Export of services: VAT zero-rated. USD figure is for reference at the stated rate.', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', 'International', 'NC', CAST(strftime('%s', date('now', '-5 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-5 days')) AS INTEGER) * 1000),
  ('inv_demo_04', 'DEMO-0004', 'Adeyemi & Co. Solicitors', 'admin@adeyemico.ng', 'Adeyemi & Co. Solicitors
Tunde Adeyemi
3 Alfred Rewane Road
Ikoyi, Lagos
Nigeria', CAST(strftime('%s', date('now', '-45 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-15 days')) AS INTEGER) * 1000, 'NGN', 'sent', '[{"name": "Brand identity package", "desc": "Logo, stationery, brand guide", "qty": 1, "unitPrice": 750000}, {"name": "Printed letterheads (box of 500)", "desc": "", "qty": 2, "unitPrice": 45000}]', '[]', 840000.0, 0.075, 0, 'value', 25000, 'Bank transfer', 0, 0, 929875.0, 'Additional charge covers courier delivery of printed items.
Still unpaid: reminder sent.', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', 'Client', 'NC', CAST(strftime('%s', date('now', '-45 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-45 days')) AS INTEGER) * 1000),
  ('inv_demo_05', 'DEMO-0005', 'Kora Foods Ltd', 'procurement@korafoods.com', 'Kora Foods Ltd
Ibrahim Musa
KM 12 Lagos-Ibadan Expressway
Ogun State
Nigeria', CAST(strftime('%s', date('now', '-20 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '+10 days')) AS INTEGER) * 1000, 'NGN', 'partially-paid', '[{"name": "Packaging design (3 SKUs)", "desc": "Front, back and side panels per SKU", "qty": 3, "unitPrice": 280000}, {"name": "Product photography", "desc": "", "qty": 1, "unitPrice": 350000}]', '[' || '{"amount": 575662.5, "date": "' || date('now', '-15 days') || '", "method": "Bank transfer", "note": "50% deposit"}' || ']', 1190000.0, 0.075, 10, 'percent', 0, 'Bank transfer', 0, 0, 1151325.0, '', 'Net 30. Late payments accrue 1.5% interest per month.', 'Client work', 'Client', 'NC', CAST(strftime('%s', date('now', '-20 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-20 days')) AS INTEGER) * 1000),
  ('inv_demo_06', 'DEMO-0006', 'Maple & Pine Studio', 'hello@mapleandpine.ca', 'Maple & Pine Studio
Olivia Tremblay
220 King Street W
Toronto, ON M5H 1K4
Canada', CAST(strftime('%s', date('now', '-35 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-5 days')) AS INTEGER) * 1000, 'NGN', 'partially-paid', '[{"name": "Illustration set", "desc": "Spot illustrations for onboarding", "qty": 12, "unitPrice": 95000}]', '[' || '{"amount": 456000.0, "date": "' || date('now', '-30 days') || '", "method": "Wire transfer", "note": "Deposit received via Wise"}' || ']', 1140000.0, 0.0, 0, 'value', 0, 'Wire transfer', 0, 1550, 1140000.0, '', 'Net 30. Late payments accrue 1.5% interest per month.', 'Client work', 'International', 'NC', CAST(strftime('%s', date('now', '-35 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-35 days')) AS INTEGER) * 1000),
  ('inv_demo_07', 'DEMO-0007', 'Brightside Media Ltd', 'accounts@brightside.co.uk', 'Brightside Media Ltd
James Whitfield
71 Shoreditch High Street
London E1 6JJ
United Kingdom', CAST(strftime('%s', date('now', '-40 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-10 days')) AS INTEGER) * 1000, 'NGN', 'paid', '[{"name": "Explainer video: storyboard & animation", "desc": "", "qty": 1, "unitPrice": 3100000}]', '[' || '{"amount": 3100000.0, "date": "' || date('now', '-12 days') || '", "method": "Wire transfer", "note": "Paid in full, agreed at USD 2,000"}' || ']', 3100000.0, 0.0, 0, 'value', 0, 'Wire transfer', 2000, 1550, 3100000.0, 'Fixed USD price agreed in the contract: the equivalent shows the agreed figure.', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', 'International', 'NC', CAST(strftime('%s', date('now', '-40 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-40 days')) AS INTEGER) * 1000),
  ('inv_demo_08', 'DEMO-0008', 'Ikeja Hardware Supplies', 'ikejahardware@gmail.com', 'Ikeja Hardware Supplies
Mr. Chinedu Eze
45 Obafemi Awolowo Way
Ikeja, Lagos
Nigeria', CAST(strftime('%s', date('now', '-30 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-16 days')) AS INTEGER) * 1000, 'NGN', 'paid', '[{"name": "POS inventory setup", "desc": "", "qty": 1, "unitPrice": 180000}, {"name": "Staff training session", "desc": "Half-day sessions", "qty": 2, "unitPrice": 40000}]', '[' || '{"amount": 139750.0, "date": "' || date('now', '-28 days') || '", "method": "Paystack", "note": "First instalment"}' || ',' || '{"amount": 139750.0, "date": "' || date('now', '-17 days') || '", "method": "Paystack", "note": "Final instalment"}' || ']', 260000.0, 0.075, 0, 'value', 0, 'Paystack', 0, 0, 279500.0, '', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', NULL, 'NC', CAST(strftime('%s', date('now', '-30 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-30 days')) AS INTEGER) * 1000),
  ('inv_demo_09', 'DEMO-0009', 'Orbit Events', 'team@orbitevents.ng', 'Orbit Events
Zainab Bello
10 Kofo Abayomi Street
Victoria Island, Lagos
Nigeria', CAST(strftime('%s', date('now', '-25 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '+5 days')) AS INTEGER) * 1000, 'NGN', 'cancelled', '[{"name": "Event microsite", "desc": "", "qty": 1, "unitPrice": 400000}, {"name": "Ticketing integration", "desc": "", "qty": 1, "unitPrice": 150000}]', '[]', 550000.0, 0.075, 0, 'value', 0, 'Bank transfer', 0, 0, 591250.0, 'Cancelled: event postponed indefinitely by the client. Kept for the numbering sequence.', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', 'Client', 'NC', CAST(strftime('%s', date('now', '-25 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-25 days')) AS INTEGER) * 1000),
  ('inv_demo_10', 'DEMO-0010', 'Delta Freight LLC', 'billing@deltafreight.com', 'Delta Freight LLC
Marcus Reed
1200 Smith Street
Houston, TX 77002
United States', CAST(strftime('%s', date('now', '-3 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '+27 days')) AS INTEGER) * 1000, 'USD', 'sent', '[{"name": "Logistics dashboard (phase 1)", "desc": "", "qty": 1, "unitPrice": 4500}, {"name": "Hosting setup", "desc": "", "qty": 1, "unitPrice": 300}]', '[]', 4800.0, 0.0, 0, 'value', 0, 'Wire transfer', 0, 1550, 4800.0, 'Invoiced in US dollars; naira equivalent shown for our records.', 'Net 30. Late payments accrue 1.5% interest per month.', 'Client work', 'International', 'NC', CAST(strftime('%s', date('now', '-3 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-3 days')) AS INTEGER) * 1000),
  ('inv_demo_11', 'DEMO-0011', 'Sunrise Schools', 'bursar@sunriseschools.edu.ng', 'Sunrise Schools
The Bursar
5 Ring Road
Ibadan, Oyo
Nigeria', CAST(strftime('%s', date('now', '-18 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-4 days')) AS INTEGER) * 1000, 'NGN', 'paid', '[{"name": "School portal licence (term 1)", "desc": "", "qty": 1, "unitPrice": 300000}]', '[' || '{"amount": 322500.0, "date": "' || date('now', '-6 days') || '", "method": "Bank transfer", "note": ""}' || ',' || '{"amount": 10000, "date": "' || date('now', '-6 days') || '", "method": "Bank transfer", "note": "Overpaid: credit to next term"}' || ']', 300000.0, 0.075, 0, 'value', 0, 'Bank transfer', 0, 0, 322500.0, '', 'Net 30. Late payments accrue 1.5% interest per month.', 'Invoices', 'Retainer', 'NC', CAST(strftime('%s', date('now', '-18 days')) AS INTEGER) * 1000, CAST(strftime('%s', date('now', '-18 days')) AS INTEGER) * 1000);
